---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector: 
    app: users-app
  ports:
    - protocol: "TCP"
      port: 3002
      nodePort: 30002
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
      - name: users-app
        image: rahulg510/e-com-users:1.0.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3002


  