---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector: 
    app: products-app
  ports:
    - protocol: "TCP"
      port: 3001
      nodePort: 30001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-app
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
      - name: products-app
        image: rahulg510/e-com-products:1.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "600m"
        ports:
        - containerPort: 3001


  